services:
  nginx_school:
    image: nginx:latest
    container_name: school_nginx
    volumes:
      - ./:/var/www/backend
      - ./_docker/images/nginx/localhost:/etc/nginx/conf.d
      - nginx_data_school:/etc/nginx
      - nginx_logs_school:/etc/nginx/logs
    ports:
      - 8001:80
    restart: always
    depends_on:
      - php_school
    networks:
      - school_network

  php_school:
    build:
      context: .
      dockerfile: ./_docker/images/php/Dockerfile
    container_name: school_php
    volumes:
      - ./:/var/www/backend
    restart: always
    networks:
      - school_network

  postgres_school:
    image: postgres:15
    container_name: school_postgres
    restart: always
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata_school:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - school_network

  redis_school:
    image: redis:latest
    container_name: school_redis
    command:
      [
          "sh",
          "-c",
          "redis-server --requirepass $${REDIS_PASSWORD}"
      ]
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data_school:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - school_network

  queue_school:
    build:
      context: .
      dockerfile: ./_docker/images/php/Dockerfile
    container_name: school_queue
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: php artisan queue:work --tries=3 --sleep=3
    depends_on:
      - php_school
      - redis_school
    networks:
      - school_network

  # Laravel scheduler (cron)
  scheduler_school:
    build:
      context: .
      dockerfile: ./_docker/images/php/Dockerfile
    container_name: school_scheduler
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    depends_on:
      - php_school
    networks:
      - school_network

networks:
  school_network:
    driver: bridge

volumes:
  nginx_data_school:
    driver: local
  nginx_logs_school:
    driver: local
  pgdata_school:
    driver: local
  redis_data_school:
    driver: local